# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/action_text-trix/all/action_text-trix.rbi
#
# action_text-trix-2.1.16

module Trix
end
class Trix::Engine < Rails::Engine
end
