# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/acts_as_tenant/all/acts_as_tenant.rbi
#
# acts_as_tenant-1.0.1

module ActsAsTenant
  def self.add_global_record_model(model); end
  def self.configuration; end
  def self.configure; end
  def self.current_tenant; end
  def self.current_tenant=(tenant); end
  def self.default_tenant; end
  def self.default_tenant=(arg0); end
  def self.fkey; end
  def self.models_with_global_records; end
  def self.mutable_tenant!(toggle); end
  def self.mutable_tenant?; end
  def self.pkey; end
  def self.polymorphic_type; end
  def self.set_tenant_klass(klass); end
  def self.should_require_tenant?; end
  def self.tenant_klass; end
  def self.test_tenant; end
  def self.test_tenant=(tenant); end
  def self.unscoped; end
  def self.unscoped=(unscoped); end
  def self.unscoped?; end
  def self.with_mutable_tenant(&block); end
  def self.with_tenant(tenant, &block); end
  def self.without_tenant(&block); end
end
class ActsAsTenant::Error < StandardError
end
module ActsAsTenant::Errors
end
class ActsAsTenant::Errors::ModelNotScopedByTenant < ActsAsTenant::Error
end
class ActsAsTenant::Errors::NoTenantSet < ActsAsTenant::Error
end
class ActsAsTenant::Errors::TenantIsImmutable < ActsAsTenant::Error
end
class ActsAsTenant::Current < ActiveSupport::CurrentAttributes
  def self.__class_attr_defaults; end
  def self.__class_attr_defaults=(new_value); end
  def self.acts_as_tenant_unscoped; end
  def self.acts_as_tenant_unscoped=(value); end
  def self.current_tenant; end
  def self.current_tenant=(value); end
  include Anonymous_Module_44
end
module Anonymous_Module_44
  def acts_as_tenant_unscoped; end
  def acts_as_tenant_unscoped=(value); end
  def current_tenant; end
  def current_tenant=(value); end
end
class ActsAsTenant::Configuration
  def job_scope; end
  def job_scope=(scope); end
  def pkey; end
  def pkey=(arg0); end
  def require_tenant; end
  def require_tenant=(arg0); end
end
module ActsAsTenant::ControllerExtensions
  def set_current_tenant_by_subdomain(tenant = nil, column = nil, subdomain_lookup: nil); end
  def set_current_tenant_by_subdomain_or_domain(tenant = nil, primary_column = nil, second_column = nil, subdomain_lookup: nil); end
  def set_current_tenant_through_filter; end
end
module ActsAsTenant::TenantHelper
  def current_tenant; end
end
module ActsAsTenant::ControllerExtensions::Filter
  def set_current_tenant(current_tenant_object); end
  extend ActiveSupport::Concern
end
module ActsAsTenant::ModelExtensions
  extend ActiveSupport::Concern
end
module ActsAsTenant::ModelExtensions::ClassMethods
  def acts_as_tenant(tenant = nil, scope = nil, **options); end
  def validates_uniqueness_to_tenant(fields, args = nil); end
end
module ActsAsTenant::ActiveJobExtensions
  def deserialize(job_data); end
  def serialize; end
end
