# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/irb/all/irb.rbi
#
# irb-1.17.0

module IRB
end
module IRB::NestingParser
  def self.open_nestings(parse_lex_result); end
  def self.parse_by_line(parse_lex_result); end
end
class IRB::NestingParser::NestingElem < Struct
  def event; end
  def event=(_); end
  def pos; end
  def pos=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def tok; end
  def tok=(_); end
end
class IRB::NestingParser::NestingVisitor < Prism::Visitor
  def close(line, column); end
  def close_closing_loc(node); end
  def close_end_keyword_loc(node); end
  def close_location(location); end
  def close_location_start(location); end
  def heredoc_open(node); end
  def heredoc_string_like(node, type); end
  def initialize; end
  def modifier_node?(node, keyword_loc); end
  def nestings; end
  def open(line, column, elem); end
  def open_location(location, type, tok); end
  def visit_array_node(node); end
  def visit_begin_node(node); end
  def visit_block_node(node); end
  def visit_block_parameters_node(node); end
  def visit_call_node(node); end
  def visit_case_match_node(node); end
  def visit_case_node(node); end
  def visit_class_node(node); end
  def visit_def_node(node); end
  def visit_defined_node(node); end
  def visit_else_node(node); end
  def visit_embedded_statements_node(node); end
  def visit_ensure_node(node); end
  def visit_for_node(node); end
  def visit_hash_node(node); end
  def visit_if_node(node); end
  def visit_in_node(node); end
  def visit_interpolated_regular_expression_node(node); end
  def visit_interpolated_string_node(node); end
  def visit_interpolated_symbol_node(node); end
  def visit_interpolated_x_string_node(node); end
  def visit_lambda_node(node); end
  def visit_module_node(node); end
  def visit_parentheses_node(node); end
  def visit_regular_expression_node(node); end
  def visit_rescue_node(node); end
  def visit_singleton_class_node(node); end
  def visit_string_node(node); end
  def visit_super_node(node); end
  def visit_symbol_node(node); end
  def visit_unless_node(node); end
  def visit_until_node(node); end
  def visit_when_node(node); end
  def visit_while_node(node); end
  def visit_x_string_node(node); end
  def visit_yield_node(node); end
end
class IRB::RubyLex
  def assignment_expression?(code, local_variables:); end
  def calc_indent_level(opens); end
  def check_code_state(code, local_variables:); end
  def check_code_syntax(code, local_variables:); end
  def check_termination_in_prev_line(code, local_variables:); end
  def code_terminated?(code, tokens, opens, local_variables:); end
  def free_indent_nesting_element?(elem); end
  def indent_difference(lines, line_results, line_index); end
  def ltype_from_open_nestings(opens); end
  def process_indent_level(parse_lex_result, lines, line_index, is_newline); end
  def self.compile_with_errors_suppressed(code, line_no: nil); end
  def self.generate_local_variables_assign_code(local_variables); end
  def self.interpolate_ripper_ignored_tokens(code, tokens); end
  def self.ripper_lex_without_warning(code, local_variables: nil); end
  def should_continue?(tokens); end
end
class IRB::RubyLex::TerminateLineInput < StandardError
  def initialize; end
end
module IRB::Color
  def self.clear(colorable: nil); end
  def self.colorable?; end
  def self.colorize(text, seq, colorable: nil); end
  def self.colorize_code(code, complete: nil, ignore_error: nil, colorable: nil, local_variables: nil); end
  def self.inspect_colorable?(obj, seen: nil); end
  def self.without_circular_ref(obj, seen:, &block); end
end
class InvalidName___Class_0x00___ColorizeVisitor_47 < Prism::Visitor
  def dispatch(location, type); end
  def initialize; end
  def tokens; end
  def visit_array_node(node); end
  def visit_def_node(node); end
  def visit_interpolated_symbol_node(node); end
  def visit_symbol_node(node); end
end
class IRB::ColorPrinter < PP
  def initialize(out, width, colorize: nil); end
  def pp(obj); end
  def self.pp(obj, out = nil, width = nil, colorize: nil); end
  def self.screen_width; end
  def text(str, width = nil); end
end
module IRB::HelperMethod
end
class IRB::HelperMethod::Base
  extend Singleton::SingletonClassMethods
  include Singleton
end
class IRB::HelperMethod::Conf < IRB::HelperMethod::Base
end
class IRB::WorkSpace
end
module IRB::HelpersContainer
end
class IRB::Inspector
end
class IRB::BaseCompletor
end
class IRB::TypeCompletor < IRB::BaseCompletor
end
class IRB::RegexpCompletor < IRB::BaseCompletor
end
module IRB::InputCompletor
end
module IRB::History
end
module IRB::HistorySavingAbility
end
class IRB::InputMethod
end
class IRB::StdioInputMethod < IRB::InputMethod
end
class IRB::FileInputMethod < IRB::InputMethod
end
class IRB::ReadlineInputMethod < IRB::StdioInputMethod
  include IRB::HistorySavingAbility
end
class IRB::RelineInputMethod < IRB::StdioInputMethod
  include IRB::HistorySavingAbility
end
class IRB::ReidlineInputMethod < IRB::RelineInputMethod
end
class IRB::OutputMethod
end
class IRB::StdioOutputMethod < IRB::OutputMethod
end
class IRB::Context
end
module IRB::Command
end
class IRB::Command::CommandArgumentError < StandardError
end
class IRB::Command::Base
end
module IRB::Command::RubyArgsExtractor
end
module IRB::Debug
end
module InvalidName___Class_0x00___SkipPathHelperForIRB_48
end
class IRB::Command::Debug < IRB::Command::Base
end
class IRB::Command::DebugCommand < IRB::Command::Debug
end
class IRB::Command::Backtrace < IRB::Command::DebugCommand
end
class IRB::Command::Break < IRB::Command::DebugCommand
end
class IRB::Command::Catch < IRB::Command::DebugCommand
end
class IRB::Command::CD < IRB::Command::Base
end
class IRB::Command::CurrentWorkingWorkspace < IRB::Command::Base
end
class IRB::Command::ChangeWorkspace < IRB::Command::Base
end
class IRB::Command::Context < IRB::Command::Base
end
class IRB::Command::Continue < IRB::Command::DebugCommand
end
class IRB::Command::Copy < IRB::Command::Base
end
class IRB::Command::Delete < IRB::Command::DebugCommand
end
class IRB::Command::DisableIrb < IRB::Command::Base
end
class IRB::SourceFinder
end
class IRB::SourceFinder::EvaluationError < StandardError
end
class IRB::SourceFinder::Source
end
class IRB::Command::Edit < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
end
class IRB::Command::Exit < IRB::Command::Base
end
class IRB::Command::Finish < IRB::Command::DebugCommand
end
class IRB::Command::ForceExit < IRB::Command::Base
end
class IRB::Command::Help < IRB::Command::Base
end
class IRB::Pager
end
class IRB::Pager::PageOverflowIO
end
class IRB::Command::History < IRB::Command::Base
end
class IRB::Command::Info < IRB::Command::DebugCommand
end
class IRB::Command::IrbInfo < IRB::Command::Base
end
class IRB::LoadAbort < Exception
end
module IRB::IrbLoader
end
class IRB::Command::LoaderCommand < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
  include IRB::IrbLoader
end
class IRB::Command::Load < IRB::Command::LoaderCommand
end
class IRB::Command::Require < IRB::Command::LoaderCommand
end
class IRB::Command::Source < IRB::Command::LoaderCommand
end
class IRB::Command::Ls < IRB::Command::Base
end
class IRB::Command::Ls::EvaluationError < StandardError
end
class IRB::Command::Ls::Output
end
class IRB::Command::Measure < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
end
class IRB::Command::Next < IRB::Command::DebugCommand
end
class IRB::Command::Workspaces < IRB::Command::Base
end
class IRB::Command::PushWorkspace < IRB::Command::Workspaces
end
class IRB::Command::PopWorkspace < IRB::Command::Workspaces
end
class IRB::Command::ShowDoc < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
end
class IRB::Command::ShowSource < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
end
class IRB::Command::Step < IRB::Command::DebugCommand
end
class IRB::Command::MultiIRBCommand < IRB::Command::Base
  include IRB::Command::RubyArgsExtractor
end
class IRB::Command::IrbCommand < IRB::Command::MultiIRBCommand
end
class IRB::Command::Jobs < IRB::Command::MultiIRBCommand
end
class IRB::Command::Foreground < IRB::Command::MultiIRBCommand
end
class IRB::Command::Kill < IRB::Command::MultiIRBCommand
end
class IRB::Command::Whereami < IRB::Command::Base
end
module IRB::ExtendCommandBundle
end
class IRB::Statement
end
class IRB::Statement::EmptyInput < IRB::Statement
end
class IRB::Statement::Expression < IRB::Statement
end
class IRB::Statement::IncorrectAlias < IRB::Statement
end
class IRB::Statement::Command < IRB::Statement
end
class IRB::Locale
end
class InvalidName___Class_0x00___Vec_49
end
class InvalidName___Class_0x00___Canvas_50
end
class InvalidName___Class_0x00___RubyModel_51
end
class IRB::Abort < Exception
end
class IRB::Irb
end
class Binding
end
