# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack-session/all/rack-session.rbi
#
# rack-session-2.1.1

module Rack
end
module Rack::Session
end
class Rack::Session::SessionId
  def cookie_value; end
  def empty?; end
  def hash_sid(sid); end
  def initialize(public_id); end
  def inspect; end
  def private_id; end
  def public_id; end
  def to_s; end
end
module Rack::Session::Abstract
end
class Rack::Session::Abstract::SessionHash
  def [](key); end
  def []=(key, value); end
  def clear; end
  def delete(key); end
  def destroy; end
  def dig(key, *keys); end
  def each(&block); end
  def empty?; end
  def exists?; end
  def fetch(key, default = nil, &block); end
  def has_key?(key); end
  def id; end
  def id=(arg0); end
  def include?(key); end
  def initialize(store, req); end
  def inspect; end
  def key?(key); end
  def keys; end
  def load!; end
  def load_for_read!; end
  def load_for_write!; end
  def loaded?; end
  def merge!(hash); end
  def options; end
  def replace(hash); end
  def self.find(req); end
  def self.set(req, session); end
  def self.set_options(req, options); end
  def store(key, value); end
  def stringify_keys(other); end
  def to_hash; end
  def update(hash); end
  def values; end
  include Enumerable
end
class Rack::Session::Abstract::Persisted
  def call(env); end
  def commit_session(req, res); end
  def commit_session?(req, session, options); end
  def context(env, app = nil); end
  def cookie_value(data); end
  def current_session_id(req); end
  def default_options; end
  def delete_session(req, sid, options); end
  def extract_session_id(request); end
  def find_session(env, sid); end
  def force_options?(options); end
  def forced_session_update?(session, options); end
  def generate_sid(secure = nil); end
  def initialize(app, options = nil); end
  def initialize_sid; end
  def key; end
  def load_session(req); end
  def loaded_session?(session); end
  def make_request(env); end
  def prepare_session(req); end
  def same_site; end
  def security_matches?(request, options); end
  def session_class; end
  def session_exists?(req); end
  def set_cookie(request, response, cookie); end
  def sid_secure; end
  def write_session(req, sid, session, options); end
end
class Rack::Session::Abstract::PersistedSecure < Rack::Session::Abstract::Persisted
  def cookie_value(data); end
  def extract_session_id(*); end
  def generate_sid(*); end
  def session_class; end
end
class Rack::Session::Abstract::PersistedSecure::SecureSessionHash < Rack::Session::Abstract::SessionHash
  def [](key); end
end
class Rack::Session::Abstract::ID < Rack::Session::Abstract::Persisted
  def delete_session(req, sid, options); end
  def find_session(req, sid); end
  def self.inherited(klass); end
  def write_session(req, sid, session, options); end
end
class Rack::Session::Encryptor
  def cipher_secret_from_message_secret(message_secret); end
  def compute_signature(data); end
  def decrypt(base64_data); end
  def deserialized_message(data); end
  def encrypt(message); end
  def initialize(secret, opts = nil); end
  def new_cipher; end
  def new_message_and_cipher_secret; end
  def serialize_payload(message); end
  def serializer; end
  def set_cipher_key(cipher, key); end
  def verify_authenticity!(data, signature); end
end
class Rack::Session::Encryptor::Error < StandardError
end
class Rack::Session::Encryptor::InvalidSignature < Rack::Session::Encryptor::Error
end
class Rack::Session::Encryptor::InvalidMessage < Rack::Session::Encryptor::Error
end
class Rack::Session::Cookie < Rack::Session::Abstract::PersistedSecure
  def coder; end
  def delete_session(req, session_id, options); end
  def encode_session_data(session); end
  def encryptors; end
  def extract_session_id(request); end
  def find_session(req, sid); end
  def initialize(app, options = nil); end
  def legacy_digest_match?(data, digest); end
  def legacy_generate_hmac(data); end
  def persistent_session_id!(data, sid = nil); end
  def secure?(options); end
  def unpacked_cookie_data(request); end
  def write_session(req, session_id, session, options); end
end
class Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(str); end
end
class Rack::Session::Cookie::Base64::Marshal < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(str); end
end
class Rack::Session::Cookie::Base64::JSON < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(obj); end
end
class Rack::Session::Cookie::Base64::ZipJSON < Rack::Session::Cookie::Base64
  def decode(str); end
  def encode(obj); end
end
class Rack::Session::Cookie::Identity
  def decode(str); end
  def encode(str); end
end
class Rack::Session::Cookie::Marshal
  def decode(str); end
  def encode(str); end
end
class Rack::Session::Cookie::SessionId < Anonymous_Delegator_46
  def cookie_value; end
  def initialize(session_id, cookie_value); end
end
