# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tailwindcss-ruby-4.2.0-arm64/all/tailwindcss-ruby-4.2.0-arm64.rbi
#
# tailwindcss-ruby-4.2.0-arm64-darwin

module Tailwindcss
end
module Tailwindcss::Ruby
  def self.executable(exe_path: nil); end
  def self.platform; end
end
module Tailwindcss::Ruby::Upstream
end
class Tailwindcss::Ruby::UnsupportedPlatformException < StandardError
end
class Tailwindcss::Ruby::ExecutableNotFoundException < StandardError
end
class Tailwindcss::Ruby::DirectoryNotFoundException < StandardError
end
