# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tailwindcss-rails/all/tailwindcss-rails.rbi
#
# tailwindcss-rails-4.4.0

module Tailwindcss
end
module Tailwindcss::Engines
  def self.bundle; end
end
class Tailwindcss::Engine < Rails::Engine
end
module Tailwindcss::Commands
  def self.command_env(verbose:); end
  def self.compile_command(debug: nil, **kwargs); end
  def self.rails_css_compressor?; end
  def self.watch_command(always: nil, **kwargs); end
end
